### ISSUE TITLE
STEALERIUM DOES NOT WORK AT ALL

### ISSUE THREAD

**Issue by PhantomPeek** [kgnfth/tumblr#1]
it says verified on telegram connection but when testing stub even on own machine nothing happens!! please fix!!

**Comment by kgnfth** [comment]
You are doing something wrong.. Add me on tg https://t.me/Teal_c

**Comment by Fabiologik** [comment]
> it says verified on telegram connection but when testing stub even on own machine nothing happens!! please fix!!

Same here nothing work ![image](https://github.com/user-attachments/assets/2b8152ef-324b-4380-9ff6-b5a6ed6f93b3)
